Add blast stub and adapt bowtie2 wrapper
sequana/sequana-wrappers pull request #45
Opened 2022-03-29 15:33 UTC by khourhin

2022-03-29 15:46 UTC, cokelaer commented on test.py
> +def test_blast_blast():
faudrait que je regarde le code, mais pourquoi blast/blast ?

2022-03-29 15:47 UTC, cokelaer commented on wrappers/blast/blast/test/Snakefile
> +        extra=""
options ici pour etre cohérent avec l'ensemble des wrappers

2022-03-29 15:50 UTC, cokelaer requested changes

2022-03-29 16:17 UTC, ddesvillechabrol approved these changes

2022-03-30 07:51 UTC, khourhin commented on test.py
> +def test_blast_blast():
J'ai garder la structure du snakemake wrapper ie blast/makeblastdb, blast/blastn, blast/blastx, et je vais voir si c'est possible d'avoir l'ensemble des blast (blastn, blastx, blastp au moins)
 dans un seul wrapper blast/blast

2022-03-31 08:22 UTC, merged