add polypolish
sequana/sequana-wrappers pull request #54
Opened 2022-07-11 11:29 UTC by cokelaer

Add polypolish and corresponding test fixing #53

2022-07-11 12:10 UTC, ddesvillechabrol approved these changes
Cool !

2022-07-11 12:24 UTC, khourhin approved these changes

2022-07-11 12:58 UTC, khourhin requested changes

2022-07-11 12:58 UTC, khourhin commented on wrappers/polypolish/wrapper.py
> +shell("polypolish {assembly} {alignment} 1>{result} {log}")
"{options}" missing

2022-07-11 18:56 UTC, cokelaer commented on wrappers/polypolish/wrapper.py
> +shell("polypolish {assembly} {alignment} 1>{result} {log}")
bien vu. fixé

2022-07-12 07:47 UTC, khourhin approved these changes

2022-07-12 09:54 UTC, merged